### ISSUE TITLE
How to use the scripts

### ISSUE THREAD

**Issue by kokolorentz** [chaoabunga/mnscripts#6]
Hello,

I got some questions about your scripts, and since I can't see another way, I'm trying it here...

First about the scripts selection...

1) There is another CHC-Masternode-setup-script, which seems bit easier to handle: 
https://github.com/jeffward01/Chaincoin-MN-SetupScript

But your chc-scripts obviously got the following advantages:

a) Your script works with Ubuntu 16.04 (eol = 04/2021), jeffward01's script just with Ubuntu 14.04 (eol = 04/2019), so the server's OS works 2 years more when using your script, right?

b) Your scripts provide masternode-updates, jeffward01's doesn't, right?

c) Your scripts provide a masternode web monitoring system, jeffward01's doesn't, right?

Do I understand this right?

But the description, how to use your scripts, is bit incomplete / confusing.
Following questions...

2) Would you recommend to prepare the server like described in the masternode setup videos (VPS on Vultr.com)?:
https://www.youtube.com/ChainCoin

3) Should the setup script run under root or another special user?

4) Should the setup script run in a special folder?

5) Should a security setup be applied as described in the mentioned videos (firewall setup) or is this part of the script?

6) Any further preparations to be done before running the script?

7) The command line for install-mn.sh requires an argument MASTERNODE_PRIVKEY.
Where is this key supposed to come from?
How should you get this MASTERNODE_PRIVKEY?

Thanks for answers!

**Comment by chaoabunga** [comment]
Hi, thanks for providing my first issue.  But it looks less like a bug and more like a cry for information.  Here're are some very good videos for you to understand the "remote-controller" masternode setup.  Once you understand that you will know you need a server ip and a masternode genkey.  You get the masternode genkey in the wallet console.  

https://www.youtube.com/playlist?list=PLhjSbfsRlpqYUlHOZOzkH1sCzYA8L2Z2J

I have a youtube channel where i give live help sometimes, if you can catch me.  but i absolutely recommend you watch Fred Yen's video to understand the "remote-controller" concept, 

https://www.youtube.com/watch?v=KSWfXdmb48c

then  you can follow the readme and do the install efforlessly.  Good luck, and you can find more help in the official chaincoin slack:

https://chaincointeam.slack.com/

-Chao

**Comment by chaoabunga** [comment]
closing issue, no response.
